sudo: required
env:
- GHCVER=7.8.4
- GHCVER=7.10.3
- GHCVER=8.0.2
- GHCVER=8.2.1
- GHCVER=head

script:
- export HLINT_ARGUMENTS=src
- curl -sL https://raw.github.com/ndmitchell/neil/master/travis.sh | sh
